title: Rebecca Wagner 
desription: Rebecca Wanger's Online Portflio
theme: minima
author: Rebecca Wagner

# Navigation Links
header_pages:
- projects.md
- cv.md
- about.md 

collections:
  projects:
    output: true